FROM ethereum/client-go:stable-amd64

COPY ./geth_settings/test_pass.txt /root/config/password.txt
COPY ./geth_settings/genesis.json /root/ethconfig/genesis.json
COPY ./geth_settings/keys /root/.ethereum/devchain/keystore

EXPOSE 8546
EXPOSE 8545

RUN geth init /root/ethconfig/genesis.json

HEALTHCHECK --interval=3s --timeout=30s --retries=3 CMD curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":1337}'

ENTRYPOINT [ "geth", "--dev", "--dev.period", "1", "--miner.gaslimit", "30000000", "--password", \
  "/root/config/password.txt", "--datadir", "/root/.ethereum/devchain", "--mine",  "--ipcdisable", \
  "--http", "--http.api", "eth,web3,personal,net", "--http.addr", "0.0.0.0", "--http.port=8545", "--http.corsdomain", "*", \
  "--ws", "--ws.origins", "*", "--ws.addr", "0.0.0.0", "--ws.port=8546", "--graphql", "--graphql.corsdomain", "*", \
  "--authrpc.vhosts", "*", "--http.vhosts", "*", \
  "--allow-insecure-unlock", "--rpc.allow-unprotected-txs", "--vmdebug", "--networkid=1337", "--rpc.txfeecap", "0", \
  "--unlock", "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266,0x70997970C51812dc3A010C7d01b50e0d17dc79C8,0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC,0x90F79bf6EB2c4f870365E785982E1f101E93b906,0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65" \
  ]