name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Only run 1 of this workflow at a time per PR
concurrency:
  group: integration-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    name: Integration Tests
    permissions:
      checks: write
      pull-requests: write
    services:
      test-geth:
        image: kalverra/test-geth
        ports:
          - 8545:8545
          - 8546:8546
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Download Go Vendor Packages
        run: go mod download
      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2
        with:
          # Optional: pass GITHUB_TOKEN to avoid rate limiting.
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests
        run: |
          set -euo pipefail
          go test -tags integration -count=1 -json -v -coverprofile=profile.cov $(go list ./...) 2>&1 | tee /tmp/gotest.log | gotestfmt
      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./profile.cov
          name: codecov-umbrella
      - name: Upload test log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error
