name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  integration:
    services:
      test-geth:
        image: kalverra/test-geth
        ports:
          - 8545:8545
          - 8546:8546
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Download Go Vendor Packages
        run: go mod download
      - name: Set up gotestfmt
        uses: haveyoudebuggedit/gotestfmt-action@v2
        with:
          # Optional: pass GITHUB_TOKEN to avoid rate limiting.
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests
        run: |
          set -euo pipefail
          go test -tags integration -count=1 -json -v -coverprofile=profile.cov $(go list ./...) 2>&1 | tee /tmp/gotest.log | gotestfmt
          cat /tmp/gotest.log
      - name: Format Results
        if: always()
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          cat /tmp/gotest.log
          go-junit-report -parser gojson -in /tmp/gotest.log -out report.xml
          cat report.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "report.xml"
      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./profile.cov
          name: codecov-umbrella
