name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit:
    services:
      test-geth:
        image: kalverra/test-geth
        ports:
          - 8545:8545
          - 8546:8546
        options: >-
          --health-cmd "curl -X POST --data '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":31337}' http://localhost:8545"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Download Go Vendor Packages
        run: go mod download
      - name: Set up gotestfmt
        uses: haveyoudebuggedit/gotestfmt-action@v2
        with:
          # Optional: pass GITHUB_TOKEN to avoid rate limiting.
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests
        run: |
          set -euo pipefail
          go test -tags integration -count=1 -json -v -coverprofile=profile.cov $(go list ./... | grep -v /contracts) 2>&1 | tee /tmp/gotest.log | gotestfmt
      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./profile.cov
          name: codecov-umbrella 

