name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Download Go Vendor Packages
        run: go mod download
      - name: Run Tests
        run: make test_fancy
      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./profile.cov
          name: codecov-umbrella 

